services:
  - type: web
    name : node-js-static
    runtime: node
    startCommand: npm start
    buildCommand: npm install
    plan: free
    region: frankfurt
    envVars:
      - key: DATABASE_URL
        fromDatabase: 
          name: users
          property: connectionString

databases:
  - name: users
    databaseName: users_app
    plan: free
    region: frankfurt
    