services:
  - type: web
    name : node-js-static
    runtime: node
    startCommand: npm run
    buildCommand: npm install
    plan: free
    region: frankfurt

databases:
  - name: users
    databaseName: users_app
    plan: free
    