services:
  - type: web
    name : render-static
    runtime: static
    buildCommand: yarn buildCommand
    staticPublishPath: ./build
    

databases:
  - name: users
    databaseName: users_app
    