services:
  - type: web
    name : render-static
    runtime: node
    startCommand: npm install
    buildCommand: npm run 
    plan: free

databases:
  - name: users
    databaseName: users_app
    plan: free
    