services:
  - type: web
    name : node-js-static
    runtime: node
    startCommand: npm install
    buildCommand: npm run 
    plan: free
    region: frankfurt

databases:
  - name: users
    databaseName: users_app
    plan: free
    